#!/usr/bin/with-contenv sh

CONFIG_FILE="/config/app.ini"

# create initial config file
if [[ ! -f "$CONFIG_FILE" ]]; then
  TMP_FILE="$(mktemp)"
  cat <<EOF >"$TMP_FILE"
RUN_USER = git

[server]
APP_DATA_PATH = /config/data
SSH_PORT      = 2222

[repository]
ROOT = /config/data/repositories
SCRIPT_TYPE = sh

[database]
TYPE = sqlite3
PATH = /config/gogs.db

[log]
MODE      = console,file
ROOT_PATH = /config/logs

[repository.upload]
TEMP_PATH = /tmp/uploads

[session]
PROVIDER_CONFIG = /config/data/sessions

[lfs]
OBJECTS_PATH = /config/data/lfs-objects

[attachment]
PATH = /config/data/attachments

[picture]
AVATAR_UPLOAD_PATH            = /config/data/avatars
REPOSITORY_AVATAR_UPLOAD_PATH = /config/data/repo-avatars
EOF

  install -m644 -o $PUID -g $PGID "$TMP_FILE" "$CONFIG_FILE"
fi

# change chdir
cd /config

# run with limited permissions
exec s6-setuidgid $PUID:$PGID /app/gogs web -c /config/app.ini
